local flash = require('flash')

vim.keymap.set("n", "s", function() flash.jump() end)
vim.keymap.set("x", "s", function() flash.jump() end)
vim.keymap.set("o", "s", function() flash.jump() end)
vim.keymap.set("n", "S", function() flash.treesitter() end)
vim.keymap.set("x", "S", function() flash.treesitter() end)
vim.keymap.set("o", "S", function() flash.treesitter() end)
vim.keymap.set("o", "r", function() flash.remote() end)
vim.keymap.set("o", "R", function() flash.treesitter_search() end)
vim.keymap.set("x", "R", function() flash.treesitter_search() end)
vim.keymap.set("c", "<c-s>", function() flash.toggle() end)
